# Generated by Django 4.1.7 on 2023-03-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
